"""initial schema

Revision ID: dfce0a8de5d9
Revises: 
Create Date: 2026-08-12 21:39:21.455786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
import app.models.base  # custom GUID/JSONB column types

# revision identifiers, used by Alembic.
revision: str = 'dfce0a8de5d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_pii',
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=64), nullable=True),
    sa.Column('dob', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('role', sa.Enum('patient', 'health_worker', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('user_id', app.models.base.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('patients',
    sa.Column('pii_ref', app.models.base.GUID(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('sex', sa.Enum('female', 'male', name='sex'), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('village_or_area', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pii_ref'], ['patient_pii.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pii_ref')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_created_by'), ['created_by'], unique=False)

    op.create_table('screenings',
    sa.Column('patient_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'analyzed', 'reviewed', name='screening_status'), nullable=False),
    sa.Column('reviewed_by', app.models.base.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenings_patient_id'), ['patient_id'], unique=False)

    op.create_table('clinical_measurements',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
    sa.Column('trestbps', sa.Integer(), nullable=False),
    sa.Column('chol', sa.Integer(), nullable=False),
    sa.Column('fbs', sa.Integer(), nullable=False),
    sa.Column('restecg', sa.Integer(), nullable=False),
    sa.Column('thalach', sa.Integer(), nullable=False),
    sa.Column('exang', sa.Integer(), nullable=False),
    sa.Column('oldpeak', sa.Float(), nullable=False),
    sa.Column('slope', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=False),
    sa.Column('thal', sa.Integer(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_table('ecg_recordings',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=False),
    sa.Column('lead_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('device_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_table('fusion_results',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.Enum('low', 'moderate', 'high', name='risk_band'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('modalities_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('uncertainty_note', sa.Text(), nullable=False),
    sa.Column('fusion_version', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_table('model_predictions',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('modality', sa.Enum('clinical', 'pcg', 'ecg', name='modality'), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id', 'modality', name='uq_prediction_per_modality')
    )
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_predictions_screening_id'), ['screening_id'], unique=False)

    op.create_table('pcg_recordings',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id')
    )
    op.create_table('referrals',
    sa.Column('screening_id', app.models.base.GUID(), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'completed', 'cancelled', name='referral_status'), nullable=False),
    sa.Column('refer_to', sa.String(length=160), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referrals_screening_id'), ['screening_id'], unique=False)

    op.create_table('explanations',
    sa.Column('prediction_id', app.models.base.GUID(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('top_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['model_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanations')
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referrals_screening_id'))

    op.drop_table('referrals')
    op.drop_table('pcg_recordings')
    with op.batch_alter_table('model_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_predictions_screening_id'))

    op.drop_table('model_predictions')
    op.drop_table('fusion_results')
    op.drop_table('ecg_recordings')
    op.drop_table('clinical_measurements')
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screenings_patient_id'))

    op.drop_table('screenings')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_created_by'))

    op.drop_table('patients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('patient_pii')
    # ### end Alembic commands ###
